modLoader="javafml"
loaderVersion="[50,)"
license="All rights reserved"
[[mods]]
modId="twigs"
version="1.21-3.2.0"
displayName="Twigs"
logoFile= "twigs.png"
authors="Ninni"
description='''
A Minecraft mod all about building, adding new and interesting materials, as well as new renditions of current vanilla blocks.

Author:
- Ninni

Contributors:
- Orcinus
- Andante

'''
[[dependencies.twigs]]
    modId="forge"
    mandatory=true
    versionRange="[50,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.twigs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21,1.22)"
    ordering="NONE"
    side="BOTH"
