package com.ninni.twigs.registry;

import net.minecraft.block.Block;
import net.minecraft.item.Item;

public class ItemRegistry
{
    public static Item reinforced_oak_planks;
    public static Item oak_bark_planks;
    public static Item oak_bark_stairs;
    public static Item oak_bark_trapdoor;
    public static Item oak_bark_door;
    public static Item oak_bark_pressure_plate;
    public static Item oak_bark_button;
    public static Item reinforced_oak_stairs;
    public static Item oak_bark_slab;
    public static Item reinforced_oak_slab;
    public static Item carved_oak;
    public static Item oak_branch;
    public static Item stripped_oak_branch;
    public static Item boulder;
    public static Item pebbles;
    public static Item black_glazed_bricks;
    public static Item blue_glazed_bricks;
    public static Item brown_glazed_bricks;
    public static Item cyan_glazed_bricks;
    public static Item gray_glazed_bricks;
    public static Item green_glazed_bricks;
    public static Item light_blue_glazed_bricks;
    public static Item light_gray_glazed_bricks;
    public static Item lime_glazed_bricks;
    public static Item magenta_glazed_bricks;
    public static Item orange_glazed_bricks;
    public static Item pink_glazed_bricks;
    public static Item purple_glazed_bricks;
    public static Item red_glazed_bricks;
    public static Item white_glazed_bricks;
    public static Item yellow_glazed_bricks;
    public static Item stone_brick_pillar;
    public static Item stone_pillar;
    public static Item cracked_stone_brick_pillar;
    public static Item mossy_stone_brick_pillar;
    public static Item polished_andesite_bricks;
    public static Item cracked_polished_andesite_bricks;
    public static Item mossy_polished_andesite_bricks;
    public static Item chiseled_polished_andesite_bricks;
    public static Item polished_andesite_pillar;
    public static Item polished_diorite_bricks;
    public static Item cracked_polished_diorite_bricks;
    public static Item mossy_polished_diorite_bricks;
    public static Item chiseled_polished_diorite_bricks;
    public static Item polished_diorite_pillar;
    public static Item polished_granite_bricks;
    public static Item cracked_polished_granite_bricks;
    public static Item mossy_polished_granite_bricks;
    public static Item chiseled_polished_granite_bricks;
    public static Item polished_granite_pillar;
    public static Item polished_andesite_brick_slab;
    public static Item polished_andesite_brick_stairs;
    public static Item polished_andesite_brick_wall;
    public static Item dark_oak_bark_planks;
    public static Item birch_bark_planks;
    public static Item acacia_bark_planks;
    public static Item jungle_bark_planks;
    public static Item spruce_bark_planks;
    public static Item warped_stem_planks;
    public static Item crimson_stem_planks;
    public static Item rock;
    public static Item oak_beam;
    public static Item stripped_oak_beam;
    public static Item acacia_bark_stairs;
    public static Item acacia_bark_slab;
    public static Item acacia_bark_trapdoor;
    public static Item acacia_bark_door;
    public static Item acacia_bark_pressure_plate;
    public static Item acacia_bark_button;
    public static Item reinforced_acacia_slab;
    public static Item reinforced_acacia_stairs;
    public static Item reinforced_acacia_planks;
    public static Item carved_acacia;
    public static Item acacia_branch;
    public static Item stripped_acacia_branch;
    public static Item acacia_beam;
    public static Item stripped_acacia_beam;
}